//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assingment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assingment()
        {
            this.as_submit = new HashSet<as_submit>();
        }
    
        public int as_id { get; set; }
        public string as_title { get; set; }
        public Nullable<int> as_sub { get; set; }
        public Nullable<int> as_batch { get; set; }
        public string as_date { get; set; }
        public string as_file { get; set; }
        public string as_desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<as_submit> as_submit { get; set; }
        public virtual batch batch { get; set; }
        public virtual st_subj st_subj { get; set; }
    }
}
