//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exam()
        {
            this.exam_result = new HashSet<exam_result>();
            this.exam_result1 = new HashSet<exam_result>();
        }
    
        public int s_id { get; set; }
        public string e_type { get; set; }
        public string e_date { get; set; }
        public Nullable<int> e_subj { get; set; }
        public Nullable<int> e_batch { get; set; }
        public string est_time { get; set; }
        public string end_time { get; set; }
        public Nullable<int> e_marks { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual st_subj st_subj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_result> exam_result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_result> exam_result1 { get; set; }
    }
}
