//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class parent_info
    {
        public int par_Id { get; set; }

        
        public string f_name { get; set; }
        public string f_contact { get; set; }

     
        public string m_name { get; set; }
        public string m_contact { get; set; }

      
        public string f_cnic { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email Must Be Provided")]
        [Display(Name = "User Email")]
        public string f_email { get; set; }
        public Nullable<int> s_id { get; set; }
    
        public virtual std_info std_info { get; set; }
    }
}
