//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_fees
    {
        public int f_id { get; set; }
        public string f_month { get; set; }
        public string f_date { get; set; }
        public Nullable<int> f_fees { get; set; }
        public Nullable<int> s_id { get; set; }
    
        public virtual std_info std_info { get; set; }
    }
}
