//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class std_add
    {
        
        public int s_add { get; set; }
        public string s_city { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = " Must Be Provided")]
        [Display(Name = "Palce Of birth")]
        public string p_o_b { get; set; }
        public string d_o_b { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = " Must Be Provided")]
        [Display(Name = "Address")]
        public string s_address { get; set; }
        public Nullable<int> s_id { get; set; }
    
        public virtual std_info std_info { get; set; }
    }
}
