//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class std_course
    {
        public int c_id { get; set; }
        public string c_name { get; set; }
        public Nullable<int> c_fees { get; set; }
        public string c_img { get; set; }
        public string c_desc { get; set; }
    }
}
