//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class std_mat
    {
        public int sm_id { get; set; }
        public Nullable<int> sm_subj { get; set; }
        public string sm_desc { get; set; }
        public string sm_file { get; set; }
        public Nullable<int> sm_batch { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual st_subj st_subj { get; set; }
    }
}
