//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class std_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public std_info()
        {
            this.parent_info = new HashSet<parent_info>();
            this.std_add = new HashSet<std_add>();
            this.st_fees = new HashSet<st_fees>();
            this.exam_result = new HashSet<exam_result>();
            this.as_submit = new HashSet<as_submit>();
        }
    
        public int s_id { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Name Must Be Provided")]
        [Display(Name = "User Name")]
        public string s_name { get; set; }
        public string s_relig { get; set; }

        
        public string s_num { get; set; }
        public string s_gender { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Email Must Be Provided")]
        [Display(Name = "User Email")]
        public string s_email { get; set; }
        public string s_pic { get; set; }

        
        public string s_pass { get; set; }

        
        public string s_cpass { get; set; }
        public Nullable<int> s_batchid { get; set; }
    
        public virtual batch batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parent_info> parent_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<std_add> std_add { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<st_fees> st_fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_result> exam_result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<as_submit> as_submit { get; set; }
    }
}
