//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_batch
    {
        public int t_batch { get; set; }
        public Nullable<int> bt_id { get; set; }
        public Nullable<int> tb_id { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual teacher_info teacher_info { get; set; }
    }
}
